name: zeda_build
on:
  schedule:
    - cron: '0 0 */1 * *'
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: categoryik/mi-lib-starter
          ref: main
      - name: Set Path for MiLib Installer
        run: |
          export PATH=/home/runner/usr/bin:$PATH
          export LD_LIBRARY_PATH=/home/runner/usr/lib:$LD_LIBRARY_PATH
      - name: "Build MiLib (COMPILER:default, STANDARD:default)"
        run: |
          ./scripts/mi-lib-install
          ./scripts/mi-lib-uninstall
      - name: "Build MiLib (COMPILER:gcc, STANDARD:c99)"
        run: |
          CC=gcc STD=c99 ./scripts/mi-lib-install
          ./scripts/mi-lib-uninstall
      - name: "Build MiLib (COMPILER:gcc, STANDARD:c++17)"
        run: |
          CC=g++ STD=c++17 ./scripts/mi-lib-install
          ./scripts/mi-lib-uninstall
